# objectid: <EXISTING_CONFIG_ID_IF_UPDATING>
scope: integration-azure
value:
  enabled: true
  description: my-monitoring-config
  version: 1.0.10
  azure:
    deploymentscope: SUBSCRIPTION
    configurationmode: ADVANCED
    deploymentmode: AUTOMATED
    subscriptionfilteringmode: INCLUDE
    credentials:
      - enabled: true
        description: Connection-Description
        # The Connection ID representing the Azure Connection object in Dynatrace
        connectionid: <PASTE_CONNECTION_ID_HERE>
        # The Application ID of the Service Principal used for this connection
        serviceprincipalid: 00000000-0000-0000-0000-000000000000
        type: FEDERATED
    locationfiltering:
      - eastus
      - eastus2euap
      - eastusstg
      - northcentralus
      - southcentralus
      - southcentralusstg
      - westcentralus
      - westus
      - westus2
      - westus3
      - canadacentral
      - canadaeast
      - mexicocentral
      - francecentral
      - francesouth
      - germanynorth
      - germanywestcentral
      - italynorth
      - northeurope
      - norwayeast
      - norwaywest
      - polandcentral
      - spaincentral
      - swedencentral
      - switzerlandnorth
      - switzerlandwest
      - uksouth
      - ukwest
      - westeurope
      - israelcentral
      - qatarcentral
      - uaecentral
      - uaenorth
      - australiacentral
      - australiacentral2
      - australiaeast
      - australiasoutheast
      - centralindia
      - eastasia
      - japaneast
      - japanwest
      - jioindiacentral
      - jioindiawest
      - koreacentral
      - koreasouth
      - newzealandnorth
      - southindia
      - southeastasia
      - westindia
      - southafricanorth
      - southafricawest
      - brazilsouth
      - brazilsoutheast
      - brazilus
    tagfiltering:
      - key: owner
        value: operations-team
        condition: INCLUDE
      - key: environment
        value: production
        condition: EXCLUDE
    tagenrichment:
      - owner
      - cost-center
    dtlabelsenrichment:
      dt.cost.costcenter:
        literal: "12345678"
        tagkey: ""
      dt.cost.product:
        literal: ""
        tagkey: cost-center
      dt.security_context:
        literal: my-security-context
        tagkey: ""
  featuresets:
  - microsoft_compute.virtualmachines_essential
  - microsoft_sql.servers.databases_user_essential
  - microsoft_storage.storageaccounts_essential
  # Add other feature sets as needed from the commented list below
# Additional feature sets to consider:
# - microsoft_app.containerapps_essential
# - microsoft_app.managedenvironments_essential
# - microsoft_appconfiguration.configurationstores_essential
# - microsoft_apimanagement.service_essential
# - microsoft_appplatform.spring_essential
# - microsoft_automation.automationaccounts_essential
# - microsoft_batch.batchaccounts_essential
# - microsoft_cache.redis_essential
# - microsoft_cache.redisenterprise_essential
# - microsoft_cdn.cdnwebapplicationfirewallpolicies_essential
# - microsoft_cdn.profiles_essential
# - microsoft_cognitiveservices.accounts_aiservices_essential
# - microsoft_cognitiveservices.accounts_anomalydetector_essential
# - microsoft_cognitiveservices.accounts_bing.customsearch_essential
# - microsoft_cognitiveservices.accounts_bing.spellcheck_v7_essential
# - microsoft_cognitiveservices.accounts_bing_autosuggest_v7_essential
# - microsoft_cognitiveservices.accounts_bing_entitysearch_essential
# - microsoft_cognitiveservices.accounts_bing_search_v7_essential
# - microsoft_cognitiveservices.accounts_computervision_essential
# - microsoft_cognitiveservices.accounts_contentmoderator_essential
# - microsoft_cognitiveservices.accounts_customvision_prediction_essential
# - microsoft_cognitiveservices.accounts_customvision_training_essential
# - microsoft_cognitiveservices.accounts_face_essential
# - microsoft_cognitiveservices.accounts_immersivereader_essential
# - microsoft_cognitiveservices.accounts_inkrecognizer_essential
# - microsoft_cognitiveservices.accounts_luis_authoring_essential
# - microsoft_cognitiveservices.accounts_luis_essential
# - microsoft_cognitiveservices.accounts_openai_essential
# - microsoft_cognitiveservices.accounts_personalizer_essential
# - microsoft_cognitiveservices.accounts_speechservices_essential
# - microsoft_cognitiveservices.accounts_textanalytics_essential
# - microsoft_cognitiveservices.accounts_texttranslation_essential
# - microsoft_compute.virtualmachinescalesets_essential
# - microsoft_containerinstance.containergroups_essential
# - microsoft_containerregistry.registries_essential
# - microsoft_containerservice.managedclusters_essential
# - microsoft_databoxedge.databoxedgedevices_essential
# - microsoft_datafactory.factories_essential
# - microsoft_datashare.accounts_essential
# - microsoft_dbformysql.flexibleservers_essential
# - microsoft_dbforpostgresql.flexibleservers_essential
# - microsoft_dbforpostgresql.serversv2_essential
# - microsoft_devices.iothubs_essential
# - microsoft_devices.provisioningservices_essential
# - microsoft_documentdb.databaseaccounts_globaldocumentdb_essential
# - microsoft_documentdb.databaseaccounts_mongodb_essential
# - microsoft_documentdb.databaseaccounts_essential
# - microsoft_eventgrid.domains_essential
# - microsoft_eventgrid.systemtopics_essential
# - microsoft_eventgrid.topics_essential
# - microsoft_eventhub.clusters_essential
# - microsoft_eventhub.namespaces_essential
# - microsoft_hdinsight.clusters_essential
# - microsoft_insights.components_essential
# - microsoft_iotcentral.iotapps_essential
# - microsoft_keyvault.vaults_essential
# - microsoft_kusto.clusters_essential
# - microsoft_logic.workflows_essential
# - microsoft_machinelearningservices.workspaces_essential
# - microsoft_maps.accounts_essential
# - microsoft_netapp.netappaccounts.capacitypools.volumes_essential
# - microsoft_netapp.netappaccounts.capacitypools_essential
# - microsoft_network.applicationgateways_essential
# - microsoft_network.azurefirewalls_essential
# - microsoft_network.connections_essential
# - microsoft_network.dnszones_essential
# - microsoft_network.expressroutecircuits_essential
# - microsoft_network.expressrouteports_essential
# - microsoft_network.frontdoors_essential
# - microsoft_network.loadbalancers_standard_essential
# - microsoft_network.loadbalancers_gateway_essential
# - microsoft_network.loadbalancers_essential
# - microsoft_network.networkinterfaces_essential
# - microsoft_network.privatednszones_essential
# - microsoft_network.publicipaddresses_essential
# - microsoft_network.trafficmanagerprofiles_essential
# - microsoft_network.virtualnetworks_essential
# - microsoft_notificationhubs.namespaces.notificationhubs_essential
# - microsoft_operationalinsights.workspaces_essential
# - microsoft_peering.peerings_essential
# - microsoft_powerbidedicated.capacities_essential
# - microsoft_recoveryservices.vaults_essential
# - microsoft_relay.namespaces_essential
# - microsoft_search.searchservices_essential
# - microsoft_servicebus.namespaces_standard_essential
# - microsoft_servicebus.namespaces_premium_essential
# - microsoft_servicebus.namespaces_essential
# - microsoft_servicefabricmesh.applications_essential
# - microsoft_signalrservice.signalr_essential
# - microsoft_sql.managedinstances_essential
# - microsoft_sql.servers.databases_user_vcore_essential
# - microsoft_sql.servers.databases_hyperscale_essential
# - microsoft_sql.servers.elasticpools_essential
# - microsoft_storage.storageaccounts.blobservices_essential
# - microsoft_storage.storageaccounts.fileservices_essential
# - microsoft_storage.storageaccounts.queueservices_essential
# - microsoft_storage.storageaccounts.tableservices_essential
# - microsoft_storagesync.storagesyncservices_essential
# - microsoft_streamanalytics.streamingjobs_essential
# - microsoft_synapse.workspaces.bigdatapools_essential
# - microsoft_synapse.workspaces.sqlpools_essential
# - microsoft_synapse.workspaces_essential
# - microsoft_vmwarecloudsimple.virtualmachines_essential
# - microsoft_web.hostingenvironments_essential
# - microsoft_web.serverfarms_essential
# - microsoft_web.sites_app_essential
# - microsoft_web.sites_functionapp_essential
# - microsoft_web.sites_functionapp_workflowapp_essential
